name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to GitHub Container Registry
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io


      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/camoroony/hypertrophy-edu-backend:latest ./backend
          docker push ghcr.io/camoroony/hypertrophy-edu-backend:latest
