name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to GitHub Container Registry
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io


      - name: Build and push backend image
        run: |
          docker buildx build --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -t ghcr.io/camoroony/hypertrophy-edu-backend:latest ./backend --push
          docker push ghcr.io/camoroony/hypertrophy-edu-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/camoroony/hypertrophy-edu-frontend:latest ./frontend
          docker push ghcr.io/camoroony/hypertrophy-edu-frontend:latest
